### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-css-frameworks-p1twXJ#1]
@egillespie Can you take a look at this? It's [hosted here](https://KatieMFritz.github.io/MI-000-SS00-000-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

Tried to do the minimum, not using my prior knowledge, to see if this is the outcome you expected. Exceptions: I used lead class on my opening paragraph, and I used two images instead of one.

**Comment by KatieMFritz** [comment]
ugh I meant to send this to @chrisvfritz! Sorry.

**Comment by KatieMFritz** [comment]
TODO: Update nav links with real links per updated lesson criteria.

**Comment by egillespie** [comment]
Do you want me to review this?

**Comment by KatieMFritz** [comment]
@egillespie No, didn't mean to tag you! Sorry.

**Comment by KatieMFritz** [comment]
Okay now it's good. :shipit:

**Comment by egillespie** [comment]
No problem. Just making sure you weren't waiting on me for anything. You should be able to edit the description if you want to change the @mention, too.
